### ISSUE TITLE
Pelvis slide joints don't seem to work

### ISSUE THREAD

**Issue by deq2** [osudrl/cassie-mujoco-sim#2]
When I run this simulation as is, for some reason the robot doesn't seem to be affected by gravity. I think possibly the pelvis joints are not working correctly for some reason. Here's a video: https://drive.google.com/file/d/18WAVZLYY2icKv7r6SWN_fa2Hg97i7mmx/view?usp=sharing

**Comment by hyparxis** [comment]
There's a function called [cassie_sim_hold](https://github.com/osudrl/cassie-mujoco-sim/blob/master/include/cassiemujoco.h#L188) that causes this behavior intentionally. I would check the code you're running for calls to that function, otherwise just manually calling [cassie_sim_release](https://github.com/osudrl/cassie-mujoco-sim/blob/master/include/cassiemujoco.h#L191) should undo it. Let me know if that helps!
